### 5. Wszystkie filamenty
GET http://localhost:8082/api/filaments

### 6. Filament o id
POST http://localhost:8082/api/filaments/ee3d26d6-9885-4d44-98fc-0ce2850ffa31
Content-Type: application/json

{
  "brand": "New Filajment",
  "diameter": "175",
  "color": "Red",
  "weight": "1000"
}

### 8. Aktualizuj filament
PUT http://localhost:8082/api/filaments/f8fa799f-b9ce-4ef2-adef-6b0c7c4408b8
Content-Type: application/json

{
  "brand": "Brand1",
  "diameter": "175",
  "color": "Red",
  "weight": "2000"
}

### 9, Usun filament
DELETE http://localhost:8082/api/filaments/f8fa799f-b9ce-4ef2-adef-6b0c7c4408b8